# services:
#     app:
#         build: ./app
#         ports:
#             - "8000:8000"
#             # ter portas abertas é ruim? como vou acessar se as portas?
#         environment:
#             - SECRET_KEY=${SECRET_KEY:-2e6e8cc741f246604c750dcc672fed67c877b2fe9f77eafaa41245ce91b5a0d3}
#             - sqlite_file_name=${sqlite_file_name:-database.db}
#             - salt=${salt:-18274393}
#             - MYSQL_USER=${MYSQL_USER:-user}
#             - MYSQL_PASSWORD=${MYSQL_PASSWORD:-cloud}
#             - DB_HOST=mysql
#             - DB_PORT=3306
#             - MYSQL_DATABASE=${MYSQL_DB:-db}
#         volumes:
#             - ./app:/usr/local/app
#             # isso permite eu fazer alterações para desenvolvimento parece ser bem top
#         depends_on:
#             mysql:
#                 condition: service_healthy
#                 restart: true

#     mysql:
#         image: mysql:8.0
#         restart: always
#         environment:
#             MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}
#             MYSQL_USER: ${MYSQL_USER:-user}
#             MYSQL_PASSWORD: ${MYSQL_PASSWORD:-cloud}
#             MYSQL_DATABASE: ${MYSQL_DB:-db}
#         healthcheck:
#             test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#             interval: 10s
#             timeout: 5s
#             retries: 10
